blank_issues_enabled: false
contact_links:
  - name: Contribution guide
    url: https://github.com/qloveyzdd/EnglishDecompiler/blob/main/CONTRIBUTING.md
    about: Please read the contribution guide before opening a new issue.
